Sprint 13, add-controllers
dimabakinec/java-shareit pull request #1
Opened 2023-05-16 08:39 UTC by dimabakinec

2023-05-16 21:31 UTC, alexache requested changes

2023-05-16 21:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingStatus.java
> +    WAITING("????? ????????????, ??????? ?????????"),
Что-то с кодировкой? Я вижу только вопросительные знаки

2023-05-16 21:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    Collection<ItemDto> getAllItemsByIdUser(long userId);
Лучше ДТО конвертировать в модель уже в сервисе, стораджу незачем знать о ДТО, и точно вне single responsibility стораджа

2023-05-16 21:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +    private void validation(long userId, long itemId) {
По код стайл гайдам сначала пишутся публичные  методы, а затем приватные

2023-05-16 21:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        userStorage.findById(userId);
Это тоже больше похоже на зону ответственности сервиса, Сторадж вещей должен заниматься хранением, а не взаимодействием с другими стораджами

2023-05-16 21:31 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +                        (item.getName().toLowerCase().contains(text.toLowerCase()) ||
text.toLowerCase() можно вызвать единожды, вместо многократного вызова

2023-05-17 07:53 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/booking/dto/BookingStatus.java
> +    WAITING("????? ????????????, ??????? ?????????"),
да, сбилась кодировка, поправил

2023-05-17 07:58 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +    private void validation(long userId, long itemId) {
поправил

2023-05-18 08:59 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +                        (item.getName().toLowerCase().contains(text.toLowerCase()) ||
исправлено

2023-05-19 09:13 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/ItemStorage.java
> +    Collection<ItemDto> getAllItemsByIdUser(long userId);
переделал

2023-05-19 09:14 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/ItemStorageImpl.java
> +        userStorage.findById(userId);
переделал

2023-05-20 12:19 UTC, alexache approved these changes

2023-05-20 12:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/error/ErrorHandler.java
> +        return new ErrorResponse("?????? ??????? ? ????????", e.getMessage());
Тут опять что-то с кодировкой

2023-05-20 12:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        validator.validateGetById(id);
Не очень оптимальный способ. И валидатор, и сервис делают запрос к стораджу. Сейчас это не очень важно, но в будущем будет неоптимально

2023-05-20 12:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        validator.validateUpdate(idOwner, id, itemDto);
Так же и здесь, получаются лишние запросы

2023-05-20 12:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorage.java
> +    Item update(long idOwner, long id, ItemDto item);
Не стоит смешивать ДТО и модели, Сторадж пусть работает только с моделью, зачем ему знать про ДТО?

2023-05-20 12:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/storage/impl/ItemInMemoryStorage.java
> +    private final UserStorage userStorage;
Уже не используется?

2023-05-20 12:19 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/service/impl/UserValidatorImpl.java
> +            if (storage.userByMail(userDto.getEmail()).getId() != id)
2 запроса к стораджу вместо одного

2023-05-22 07:41 UTC, merged