Add bookings
dimabakinec/java-shareit pull request #2
Opened 2023-05-31 10:18 UTC by dimabakinec

2023-06-02 13:30 UTC, alexache requested changes

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("Select b " +
Многие из этих custom query можно заменить на просто query через именование метода, здесь не такие сложные запросы

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private User validUserById(Long userId) {
сначала принято писать публичные методы. и только потом приватные

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        List<Booking> bookingList = bookingRepository.getBookingDate(bookingDtoRequest.getItemId(),
Достаточно запросом проверять что exists бронирования, нежели получать список, который нигде не используется

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private ItemDtoResponse item; // вещь, которую пользователь бронирует;
Лучше использовать свои небольшие вложенные ДТО классы для сущностей вещей, пользователей нежели полагаться на другие ДТО, которые могут иметь нерелевантные поля

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> + * TODO Sprint add-controllers.
Комментарий либо должен быть осмысленным, либо лучше удалить

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Booking> bookingList = new ArrayList<>();
Можно обойтись с Collections.emptyList()

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@EqualsAndHashCode
Эта аннотация (и любые автосгенерированные equals/hashcode не подходит для JPA моделей

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@Data
Включает в себя equals/hashcode что недопустимо для JPA моделей

2023-06-02 13:30 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Нельзя использовать эту аннотацию на JPA моделях

2023-06-03 07:44 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private User validUserById(Long userId) {
fixed

2023-06-03 07:49 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> + * TODO Sprint add-controllers.
fixed

2023-06-05 08:59 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("Select b " +
fixed

2023-06-05 09:10 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/request/ItemRequest.java
> +@Data
не совсем понял что нужно сделать

2023-06-05 09:20 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@ToString ? fixed

2023-06-05 09:23 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@EqualsAndHashCode
fixed

2023-06-05 09:58 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        List<Booking> bookingList = new ArrayList<>();
fixed

2023-06-05 13:24 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/booking/dto/BookingDto.java
> +    private ItemDtoResponse item; // вещь, которую пользователь бронирует;
добавлены ДТО для User и Item

2023-06-06 07:23 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +        List<Booking> bookingList = bookingRepository.getBookingDate(bookingDtoRequest.getItemId(),
честно говоря так и не понял как сделать, убрал совсем - тесты проходит

2023-06-06 20:50 UTC, alexache commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("Select b " +
Не увидел изменения в этой части

2023-06-06 20:53 UTC, alexache approved these changes

2023-06-06 21:09 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/booking/BookingRepository.java
> +    @Query("Select b " +
не понимаю что происходит! я в своем репе и в этой ветке вижу измененный файл а почему ты мне показываешь старый файл?

2023-06-06 21:12 UTC, merged