Add item requests
dimabakinec/java-shareit pull request #3
Opened 2023-06-12 17:24 UTC by dimabakinec

2023-06-15 19:25 UTC, alexache requested changes

2023-06-15 19:25 UTC, alexache commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private User validUser(Long id) {
Приватные методы принято писать после публичных

2023-06-15 19:25 UTC, alexache commented on src/main/resources/application.properties
> +# spring.config.activate.on-profile=ci,test
Зачем это выключать?

2023-06-15 19:25 UTC, alexache commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.item.name", is(bookingDto.getItem().getName())));
Будет еще полезно подсчитывать количество вызовов сервиса (что именно 1) с  помощью метода verify(), Это касается не только этого тест метода, но и остальных

2023-06-15 19:25 UTC, alexache commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    ObjectMapper mapper;
Модификаторы доступа стоит добавить

2023-06-16 08:27 UTC, dimabakinec commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +    private User validUser(Long id) {
fixed

2023-06-16 08:30 UTC, dimabakinec commented on src/main/resources/application.properties
> +# spring.config.activate.on-profile=ci,test
fixed: есть перманентная ошибка прохождения тестов в кол-ве 12 штук, но то она есть то ее нет, как будто БД не очищается, с наставником так и не поняли что это

2023-06-16 08:54 UTC, dimabakinec commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    ObjectMapper mapper;
fixed

2023-06-19 12:47 UTC, dimabakinec commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTest.java
> +                .andExpect(jsonPath("$.item.name", is(bookingDto.getItem().getName())));
fixed

2023-06-20 20:30 UTC, merged