Sprint 16
dimabakinec/java-shareit pull request #4
Opened 2023-06-26 07:12 UTC by dimabakinec

2023-06-29 20:28 UTC, alexache requested changes

2023-06-29 20:28 UTC, alexache commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
Мапа из одного элемента не требуется, можно обойтись подстановкой аргументов

2023-06-29 20:28 UTC, alexache commented on pom.xml
> +    </modules>
У основного модуля не должно быть зависимостей, только через dependencyManagement задавать версии

2023-06-30 13:38 UTC, dimabakinec commented on gateway/src/main/java/ru/practicum/shareit/booking/BookingClient.java
> +        Map<String, Object> parameters = Map.of(
fixed

2023-06-30 21:22 UTC, dimabakinec commented on pom.xml
> +    </modules>
fixed

2023-07-01 08:48 UTC, alexache requested changes

2023-07-01 08:48 UTC, alexache commented on server/pom.xml
> +            <groupId>jakarta.validation</groupId>
В модуле сервиса не должно оставаться никаких валидации, и, соответственно, зависимостей от библиотек валидации

2023-07-01 23:41 UTC, dimabakinec commented on server/pom.xml
> +            <groupId>jakarta.validation</groupId>
fixed

2023-07-02 09:38 UTC, alexache requested changes

2023-07-02 09:38 UTC, alexache commented on pom.xml
> +<!--	<dependencyManagement>-->
Как-то мы ходим кругами. У родительского модуля не должно быть своих зависимостей, только выставление зависимостей для под-модулей. В прошлый раз было уже правильно

2023-07-02 09:38 UTC, alexache commented on pom.xml
> +				<artifactId>spring-boot-starter-validation</artifactId>
Эта зависимость у тебя появляется в модуле сервиса тогда, чего не должно быть. У каждого модуля должны быть заданы свои зависимости, роль родительского модуля в задании версий зависимостей

2023-07-02 14:36 UTC, dimabakinec commented on pom.xml
> +<!--	<dependencyManagement>-->
вернул назад

2023-07-02 14:47 UTC, dimabakinec commented on pom.xml
> +				<artifactId>spring-boot-starter-validation</artifactId>
я не знал про валидацию ((

2023-07-02 14:49 UTC, dimabakinec commented
проверь пожалуйста, сегодня последний день...

2023-07-02 16:45 UTC, alexache approved these changes

2023-07-03 07:01 UTC, merged